sudo: true
services:
- docker
script:
# Build the initrd
- docker build -t hyperstart-build .
- docker run -it -v $(readlink -f .):/src -w /src hyperstart-build
# Do a dockerized version of the hyepr start kernel build
- cd build
- docker build -t hyperstart-dev:latest .
- docker run --rm hyperstart-dev:latest cat /root/build/result/kernel >kernel.new && mv -f kernel.new kernel
- docker run --rm hyperstart-dev:latest cat /root/build/result/modules.tar >modules.tar
- mv kernel_config kernel_config.old
- docker run --rm hyperstart-dev:latest cat /root/build/result/kernel_config >kernel_config
